export type Locale = "en" | "zh";

export type CopyDictionary = {
  nav: { models: string; pricing: string; docs: string; company: string; contact: string; console: string; infrastructure: string; trust: string; status: string; faq: string; deploymentReview: string; getTokens: string; openMenu: string; closeMenu: string; skipToContent: string; primaryLabel: string; mobileLabel: string };
  home: { kicker: string; title: string; accent: string; lead: string; launchStatus: string; explore: string; viewPricing: string; pathsLabel: string; developerEyebrow: string; developerPath: string; developerDescription: string; enterpriseEyebrow: string; enterprisePath: string; enterpriseDescription: string; proofLabel: string; activeRoutes: string; contextAvailable: string; illustrativeAvailability: string; modelsTitle: string; modelsLead: string; startingInputRate: string; creditTitle: string; creditLead: string; starterPack: string; builderPack: string; scalePack: string; accountCredit: string; paygCredit: string; includesBonus: string; bonusCredit: string; consoleTitle: string; consoleLead: string; finalTitle: string; finalLead: string; getStarted: string; stepsKicker: string; stepsTitle: string; steps: { discover: string; review: string; request: string } };
  models: { kicker: string; title: string; lead: string; search: string; all: string; coding: string; reasoning: string; general: string; multilingual: string; vision: string; image: string; audio: string; embedding: string; noResults: string; clearFilters: string; unavailable: string; available: string; enabled: string; context: string; speed: string; fast: string; balanced: string; deep: string; input: string; output: string; tools: string; structuredOutput: string; reasoningCapability: string; streaming: string; maxOutput: string; provenance: string; servingRole: string; region: string; modelId: string; availability: string; details: string };
  pricing: { kicker: string; title: string; lead: string; demoNotice: string; calculator: string; selectModel: string; inputTokens: string; outputTokens: string; estimate: string; invalid: string; ratesTitle: string; ratesRegionLabel: string; ratesScrollCue: string };
  docs: { kicker: string; title: string; lead: string; quickStart: string; baseUrl: string; apiKey: string; chooseModel: string; curl: string; python: string; javascript: string; copy: string; copied: string };
  console: { demo: string; previewLabel: string; previewDescription: string; title: string; balance: string; sevenDay: string; tokens: string; illustrativeSpend: string; modelSplit: string; recent: string; apiKey: string; copy: string; copied: string; noUsage: string; noRecent: string };
  enquiry: { kicker: string; title: string; lead: string; interestLabel: string; interestPlaceholder: string; launchAccess: string; infrastructure: string; partnership: string; messageLabel: string; messageHint: string; submit: string; interestRequired: string; confirmation: string; localNotice: string; companyLink: string };
  checkout: { title: string; choose: string; review: string; complete: string; back: string; next: string; close: string; demoOnly: string; launchNotice: string; requestComplete: string };
  footer: { label: string; navigation: string; product: string; companyGroup: string; policies: string; about: string; status: string; terms: string; privacy: string };
  shared: { perMillionInput: string; perMillionOutput: string; perImage: string; perMinute: string; illustrative: string; temporarilyUnavailable: string; language: string; copyUnavailable: string; ready: string; preview: string; preparation: string; notReady: string };
};

export const COPY: Record<Locale, CopyDictionary> = {
  en: {
    nav: { models: "Models", pricing: "Pricing", docs: "Docs", company: "Company", contact: "Contact", console: "Console", infrastructure: "Infrastructure", trust: "Trust", status: "Status", faq: "FAQ", deploymentReview: "Deployment review", getTokens: "Get API access", openMenu: "Open menu", closeMenu: "Close menu", skipToContent: "Skip to main content", primaryLabel: "Primary navigation", mobileLabel: "Mobile navigation" },
    home: { kicker: "The open model power layer", title: "Every model.", accent: "One power core.", lead: "Build, test, and scale with leading open AI models through one clean endpoint and infrastructure engineered for momentum.", launchStatus: "API is live — one key, pay per use", explore: "Explore the marketplace", viewPricing: "View pricing", pathsLabel: "Choose your path", developerEyebrow: "Developer access", developerPath: "Explore model access", developerDescription: "Compare models, review indicative rates, and join launch access.", enterpriseEyebrow: "Enterprise collaboration", enterprisePath: "Talk to infrastructure", enterpriseDescription: "Review public context and explore a future conversation.", proofLabel: "Marketplace proof points", activeRoutes: "active model routes", contextAvailable: "context available", illustrativeAvailability: "illustrative availability", modelsTitle: "Route every task to the right mind.", modelsLead: "One engineered layer for coding, reasoning, multilingual work, and production workloads.", startingInputRate: "Illustrative starting input rate", creditTitle: "Explore indicative launch packages.", creditLead: "Review indicative package examples before requesting non-binding launch access.", starterPack: "Starter", builderPack: "Builder", scalePack: "Scale", accountCredit: "indicative account credit", paygCredit: "Indicative launch package", includesBonus: "Includes", bonusCredit: "indicative launch bonus", consoleTitle: "Your power, clearly accounted for.", consoleLead: "Large totals and restrained usage signals keep the important information clear.", finalTitle: "Put intelligence in motion.", finalLead: "One API. One balance. Every open model powered by one core.", getStarted: "Get started", stepsKicker: "Get started", stepsTitle: "Access in three steps.", steps: { discover: "Compare live models and rates", review: "Estimate your usage", request: "Get your API key" } },
    models: { kicker: "Model marketplace", title: "Choose the mind for the task.", lead: "Compare open model families without switching providers.", search: "Search models", all: "All", coding: "Coding", reasoning: "Reasoning", general: "General", multilingual: "Multilingual", vision: "Vision", image: "Image", audio: "Audio", embedding: "Embedding", noResults: "No models match this search. Clear the query or choose another category.", clearFilters: "Clear filters", unavailable: "Temporarily unavailable", available: "Available", enabled: "Enabled", context: "Context", speed: "Speed", fast: "Fast", balanced: "Balanced", deep: "Deep", input: "Input", output: "Output", tools: "Tool use", structuredOutput: "Structured output", reasoningCapability: "Reasoning", streaming: "Streaming", maxOutput: "Maximum output", provenance: "Provenance", servingRole: "Serving role", region: "Deployment region", modelId: "Model ID", availability: "Availability", details: "details" },
    pricing: { kicker: "Prepaid pricing", title: "Pay per use. No subscription.", lead: "Live token rates for every model — billed from your prepaid balance, exactly as listed.", demoNotice: "Billing is pay-per-use from your prepaid balance. Top up with redeem codes.", calculator: "Estimate usage", selectModel: "Select a model", inputTokens: "Input tokens", outputTokens: "Output tokens", estimate: "Estimated cost", invalid: "Enter non-negative token amounts.", ratesTitle: "Model rates", ratesRegionLabel: "Model rate comparison", ratesScrollCue: "Scroll horizontally to compare every rate column." },
    docs: { kicker: "Quick start", title: "One endpoint. Familiar tools.", lead: "Use the OpenAI-compatible format your application already understands.", quickStart: "Quick start", baseUrl: "Base URL", apiKey: "Demo API key", chooseModel: "Choose a model", curl: "cURL", python: "Python", javascript: "JavaScript", copy: "Copy", copied: "Copied" },
    console: { demo: "Demo console", previewLabel: "Launch preview — illustrative only", previewDescription: "Local display only. No account, funded balance, usable API key, live API, or live usage.", title: "Usage without the noise.", balance: "Available balance", sevenDay: "Seven-day usage", tokens: "tokens", illustrativeSpend: "Illustrative spend", modelSplit: "Model split", recent: "Recent requests", apiKey: "Demo API key", copy: "Copy", copied: "Copied", noUsage: "No usage yet. Your first demo request will appear here.", noRecent: "No recent requests yet. Demo requests will appear here." },
    enquiry: { kicker: "Enterprise path", title: "Deployment review", lead: "Choose a non-binding interest for future deployment planning. This review stays entirely in your browser.", interestLabel: "I am interested in", interestPlaceholder: "Choose a deployment interest", launchAccess: "Launch access", infrastructure: "Infrastructure planning", partnership: "Model partnership", messageLabel: "Optional context", messageHint: "Optional, local to this page, and never transmitted.", submit: "Submit deployment review", interestRequired: "Choose an interest area.", confirmation: "Nothing was sent or reserved.", localNotice: "This deployment review stays in your browser. No information is transmitted or persisted, and no account, order, reservation, or commercial commitment is created.", companyLink: "Read our public company context" },
    checkout: { title: "Request launch access", choose: "Choose an access interest", review: "Review local interest", complete: "Launch-access review completed locally.", back: "Back", next: "Continue", close: "Close", demoOnly: "This local interest creates no order or charge. It is not transmitted or persisted.", launchNotice: "This local interest creates no order or charge. It is not transmitted or persisted.", requestComplete: "This demonstration does not provide service access or a commercial commitment." },
    footer: { label: "Footer", navigation: "Footer navigation", product: "Product", companyGroup: "Company", policies: "Policies", about: "About", status: "Status", terms: "Terms", privacy: "Privacy" },
    shared: { perMillionInput: "per 1M input", perMillionOutput: "per 1M output", perImage: "per image", perMinute: "per minute of audio", illustrative: "Illustrative data", temporarilyUnavailable: "Temporarily unavailable", language: "Language", copyUnavailable: "Copy unavailable", ready: "Ready", preview: "Preview", preparation: "In preparation", notReady: "Not ready" },
  },
  zh: {
    nav: { models: "模型", pricing: "價格", docs: "文件", company: "公司", contact: "聯絡", console: "控制台", infrastructure: "基礎設施", trust: "信任", status: "狀態", faq: "常見問題", deploymentReview: "部署審查", getTokens: "取得 API 存取", openMenu: "開啟選單", closeMenu: "關閉選單", skipToContent: "跳至主要內容", primaryLabel: "主要導覽", mobileLabel: "行動版導覽" },
    home: { kicker: "開源模型運算核心", title: "所有模型，", accent: "共享一個核心。", lead: "透過單一端點與專為成長打造的基礎設施，建置、測試並擴展領先的開源 AI 模型。", launchStatus: "API 已上線 — 一把金鑰，按量計費", explore: "探索模型市集", viewPricing: "查看價格", pathsLabel: "選擇你的路徑", developerEyebrow: "開發者存取", developerPath: "探索模型存取", developerDescription: "比較模型、查看指示性費率，並加入啟動存取。", enterpriseEyebrow: "企業合作", enterprisePath: "洽談基礎設施", enterpriseDescription: "查看公開脈絡，探索未來合作對話。", proofLabel: "市集成效數據", activeRoutes: "啟用中的模型路由", contextAvailable: "可用上下文", illustrativeAvailability: "展示可用率", modelsTitle: "讓每項任務使用最適合的模型。", modelsLead: "一套工程化服務層，涵蓋程式開發、推理、多語言與正式工作負載。", startingInputRate: "展示起始輸入費率", creditTitle: "探索指示性啟動方案。", creditLead: "先查看指示性方案範例，再提出無約束力的啟動存取請求。", starterPack: "入門", builderPack: "建置", scalePack: "規模", accountCredit: "指示性帳戶額度", paygCredit: "指示性啟動方案", includesBonus: "包含", bonusCredit: "指示性啟動加碼", consoleTitle: "每一份算力，都清楚可見。", consoleLead: "大型總額與克制的用量訊號，讓重要資訊保持清楚。", finalTitle: "讓智慧開始運轉。", finalLead: "一套 API、一個餘額，所有開源模型由同一核心驅動。", getStarted: "開始使用", stepsKicker: "開始使用", stepsTitle: "三步驟取得存取。", steps: { discover: "比較即時模型與費率", review: "估算你的用量", request: "取得你的 API 金鑰" } },
    models: { kicker: "模型市集", title: "為任務選擇正確的智慧。", lead: "無需切換供應商，就能比較各類開源模型。", search: "搜尋模型", all: "全部", coding: "程式開發", reasoning: "推理", general: "通用", multilingual: "多語言", vision: "視覺", image: "影像", audio: "音訊", embedding: "嵌入", noResults: "找不到符合條件的模型。請清除搜尋或選擇其他分類。", clearFilters: "清除篩選", unavailable: "暫時無法使用", available: "可用", enabled: "已啟用", context: "上下文", speed: "速度", fast: "快速", balanced: "均衡", deep: "深度", input: "輸入", output: "輸出", tools: "工具呼叫", structuredOutput: "結構化輸出", reasoningCapability: "推理", streaming: "串流", maxOutput: "最大輸出", provenance: "來源", servingRole: "服務角色", region: "部署區域", modelId: "模型 ID", availability: "可用性", details: "詳細資料" },
    pricing: { kicker: "預付價格", title: "按量計費，無需訂閱。", lead: "所有模型的即時 Token 費率 — 從預付餘額扣款，照表收費。", demoNotice: "計費方式為預付餘額按量計費，可用儲值碼加值。", calculator: "估算用量", selectModel: "選擇模型", inputTokens: "輸入 Token", outputTokens: "輸出 Token", estimate: "預估費用", invalid: "請輸入非負數的 Token 數量。", ratesTitle: "模型費率", ratesRegionLabel: "模型費率比較", ratesScrollCue: "水平捲動以比較所有費率欄位。" },
    docs: { kicker: "快速開始", title: "一個端點，熟悉的工具。", lead: "沿用應用程式已熟悉的 OpenAI 相容格式。", quickStart: "快速開始", baseUrl: "基礎 URL", apiKey: "展示 API Key", chooseModel: "選擇模型", curl: "cURL", python: "Python", javascript: "JavaScript", copy: "複製", copied: "已複製" },
    console: { demo: "展示控制台", previewLabel: "啟動預覽 — 僅供展示", previewDescription: "僅為本機顯示。沒有帳戶、已儲值餘額、可用 API Key、即時 API 或即時用量。", title: "清楚用量，不被雜訊干擾。", balance: "可用餘額", sevenDay: "七日用量", tokens: "詞元", illustrativeSpend: "展示支出", modelSplit: "模型分布", recent: "近期請求", apiKey: "展示 API Key", copy: "複製", copied: "已複製", noUsage: "目前尚無用量，第一筆展示請求會顯示在這裡。", noRecent: "目前尚無近期請求，展示請求會顯示在這裡。" },
    enquiry: { kicker: "企業路徑", title: "部署審查", lead: "選擇未來部署規劃的非約束性意向。此審查完全保留在你的瀏覽器中。", interestLabel: "我想洽詢", interestPlaceholder: "選擇部署意向", launchAccess: "啟動存取", infrastructure: "基礎設施規劃", partnership: "模型合作", messageLabel: "補充說明（選填）", messageHint: "選填，僅保留在此頁面，不會傳送。", submit: "送出部署審查", interestRequired: "請選擇洽詢類型。", confirmation: "未傳送或保留任何資訊。", localNotice: "此部署審查只會保留在瀏覽器中。系統不會傳送或保存資訊，也不會建立帳戶、訂單、容量保留或商業承諾。", companyLink: "閱讀公開公司脈絡" },
    checkout: { title: "申請啟動存取", choose: "選擇存取意向", review: "確認本機意向", complete: "啟動存取審查已在本機完成。", back: "返回", next: "繼續", close: "關閉", demoOnly: "此本機意向不會建立訂單或收費，也不會傳送或保存。", launchNotice: "此本機意向不會建立訂單或收費，也不會傳送或保存。", requestComplete: "此展示不提供服務存取，也不會形成商業承諾。" },
    footer: { label: "頁尾", navigation: "頁尾導覽", product: "產品", companyGroup: "公司", policies: "政策", about: "關於", status: "服務狀態", terms: "使用條款", privacy: "隱私權" },
    shared: { perMillionInput: "每百萬輸入 Token", perMillionOutput: "每百萬輸出 Token", perImage: "每張圖片", perMinute: "每分鐘音訊", illustrative: "展示資料", temporarilyUnavailable: "暫時無法使用", language: "語言", copyUnavailable: "無法複製", ready: "已就緒", preview: "預覽", preparation: "準備中", notReady: "尚未就緒" },
  },
};
