export type Locale = "en" | "zh";

export type CopyDictionary = {
  nav: { models: string; pricing: string; docs: string; console: string; getTokens: string; openMenu: string; closeMenu: string };
  home: { kicker: string; title: string; accent: string; lead: string; explore: string; viewPricing: string; modelsTitle: string; modelsLead: string; creditTitle: string; creditLead: string; consoleTitle: string; consoleLead: string; finalTitle: string; finalLead: string };
  models: { kicker: string; title: string; lead: string; search: string; all: string; coding: string; reasoning: string; general: string; multilingual: string; noResults: string; unavailable: string; context: string; speed: string; input: string; output: string; tools: string; modelId: string };
  pricing: { kicker: string; title: string; lead: string; demoNotice: string; calculator: string; selectModel: string; inputTokens: string; outputTokens: string; estimate: string; invalid: string; ratesTitle: string };
  docs: { kicker: string; title: string; lead: string; quickStart: string; baseUrl: string; apiKey: string; chooseModel: string; curl: string; python: string; javascript: string; copy: string; copied: string };
  console: { demo: string; title: string; balance: string; addCredit: string; sevenDay: string; modelSplit: string; recent: string; apiKey: string; copy: string; copied: string; noUsage: string };
  checkout: { title: string; choose: string; review: string; complete: string; back: string; next: string; close: string; demoOnly: string };
  shared: { perMillionInput: string; perMillionOutput: string; illustrative: string; temporarilyUnavailable: string; language: string; copyUnavailable: string };
};

export const COPY: Record<Locale, CopyDictionary> = {
  en: {
    nav: { models: "Models", pricing: "Pricing", docs: "Docs", console: "Console", getTokens: "Get tokens", openMenu: "Open menu", closeMenu: "Close menu" },
    home: { kicker: "The open model power layer", title: "Every model.", accent: "One power core.", lead: "Build, test, and scale with leading open AI models through one clean endpoint, one prepaid balance, and infrastructure engineered for momentum.", explore: "Explore the marketplace", viewPricing: "View pricing", modelsTitle: "Route every task to the right mind.", modelsLead: "One engineered layer for coding, reasoning, multilingual work, and production workloads.", creditTitle: "Start with ten. Scale without friction.", creditLead: "Every pack becomes flexible account credit across the full catalog.", consoleTitle: "Your power, clearly accounted for.", consoleLead: "Large totals and restrained usage signals keep the important information clear.", finalTitle: "Put intelligence in motion.", finalLead: "One API. One balance. Every open model powered by one core." },
    models: { kicker: "Model marketplace", title: "Choose the mind for the task.", lead: "Compare open model families without switching providers.", search: "Search models", all: "All", coding: "Coding", reasoning: "Reasoning", general: "General", multilingual: "Multilingual", noResults: "No models match this search. Clear the query or choose another category.", unavailable: "Temporarily unavailable", context: "Context", speed: "Speed", input: "Input", output: "Output", tools: "Tool use", modelId: "Model ID" },
    pricing: { kicker: "Illustrative pricing", title: "Predictable spend. No subscription.", lead: "Fund one balance and spend it at each model’s published token rate.", demoNotice: "Showcase prices only — no purchase or live billing occurs on this site.", calculator: "Estimate usage", selectModel: "Select a model", inputTokens: "Input tokens", outputTokens: "Output tokens", estimate: "Estimated cost", invalid: "Enter non-negative token amounts.", ratesTitle: "Model rates" },
    docs: { kicker: "Quick start", title: "One endpoint. Familiar tools.", lead: "Use the OpenAI-compatible format your application already understands.", quickStart: "Quick start", baseUrl: "Base URL", apiKey: "Demo API key", chooseModel: "Choose a model", curl: "cURL", python: "Python", javascript: "JavaScript", copy: "Copy", copied: "Copied" },
    console: { demo: "Demo console", title: "Usage without the noise.", balance: "Available balance", addCredit: "Add credit", sevenDay: "Seven-day usage", modelSplit: "Model split", recent: "Recent requests", apiKey: "Demo API key", copy: "Copy", copied: "Copied", noUsage: "No usage yet. Your first demo request will appear here." },
    checkout: { title: "Add Power credit", choose: "Choose a pack", review: "Review demo order", complete: "Demo checkout complete", back: "Back", next: "Continue", close: "Close", demoOnly: "Demonstration only. No payment or personal information is collected." },
    shared: { perMillionInput: "per 1M input", perMillionOutput: "per 1M output", illustrative: "Illustrative data", temporarilyUnavailable: "Temporarily unavailable", language: "Language", copyUnavailable: "Copy unavailable" },
  },
  zh: {
    nav: { models: "模型", pricing: "價格", docs: "文件", console: "控制台", getTokens: "購買額度", openMenu: "開啟選單", closeMenu: "關閉選單" },
    home: { kicker: "開源模型運算核心", title: "所有模型，", accent: "共享一個核心。", lead: "透過單一端點、單一預付餘額與專為成長打造的基礎設施，建置、測試並擴展領先的開源 AI 模型。", explore: "探索模型市集", viewPricing: "查看價格", modelsTitle: "讓每項任務使用最適合的模型。", modelsLead: "一套工程化服務層，涵蓋程式開發、推理、多語言與正式工作負載。", creditTitle: "十美元開始，無摩擦擴展。", creditLead: "每個方案都會轉為全模型目錄通用的帳戶額度。", consoleTitle: "每一份算力，都清楚可見。", consoleLead: "大型總額與克制的用量訊號，讓重要資訊保持清楚。", finalTitle: "讓智慧開始運轉。", finalLead: "一套 API、一個餘額，所有開源模型由同一核心驅動。" },
    models: { kicker: "模型市集", title: "為任務選擇正確的智慧。", lead: "無需切換供應商，就能比較各類開源模型。", search: "搜尋模型", all: "全部", coding: "程式開發", reasoning: "推理", general: "通用", multilingual: "多語言", noResults: "找不到符合條件的模型。請清除搜尋或選擇其他分類。", unavailable: "暫時無法使用", context: "上下文", speed: "速度", input: "輸入", output: "輸出", tools: "工具呼叫", modelId: "模型 ID" },
    pricing: { kicker: "展示價格", title: "支出可預期，無需訂閱。", lead: "儲值一個餘額，依各模型公開的 Token 費率使用。", demoNotice: "價格僅供展示；本站不會進行購買或真實計費。", calculator: "估算用量", selectModel: "選擇模型", inputTokens: "輸入 Token", outputTokens: "輸出 Token", estimate: "預估費用", invalid: "請輸入非負數的 Token 數量。", ratesTitle: "模型費率" },
    docs: { kicker: "快速開始", title: "一個端點，熟悉的工具。", lead: "沿用應用程式已熟悉的 OpenAI 相容格式。", quickStart: "快速開始", baseUrl: "Base URL", apiKey: "展示 API Key", chooseModel: "選擇模型", curl: "cURL", python: "Python", javascript: "JavaScript", copy: "複製", copied: "已複製" },
    console: { demo: "展示控制台", title: "清楚用量，不被雜訊干擾。", balance: "可用餘額", addCredit: "增加額度", sevenDay: "七日用量", modelSplit: "模型分布", recent: "近期請求", apiKey: "展示 API Key", copy: "複製", copied: "已複製", noUsage: "目前尚無用量，第一筆展示請求會顯示在這裡。" },
    checkout: { title: "增加 Power 額度", choose: "選擇方案", review: "確認展示訂單", complete: "展示結帳完成", back: "返回", next: "繼續", close: "關閉", demoOnly: "僅供展示，不會收集付款或個人資訊。" },
    shared: { perMillionInput: "每百萬輸入 Token", perMillionOutput: "每百萬輸出 Token", illustrative: "展示資料", temporarilyUnavailable: "暫時無法使用", language: "語言", copyUnavailable: "無法複製" },
  },
};
