export type Locale = "en" | "zh";

export type CopyDictionary = {
  nav: { models: string; pricing: string; docs: string; company: string; console: string; getTokens: string; openMenu: string; closeMenu: string; skipToContent: string; primaryLabel: string; mobileLabel: string };
  home: { kicker: string; title: string; accent: string; lead: string; launchStatus: string; explore: string; viewPricing: string; proofLabel: string; activeRoutes: string; contextAvailable: string; illustrativeAvailability: string; modelsTitle: string; modelsLead: string; startingInputRate: string; creditTitle: string; creditLead: string; starterPack: string; builderPack: string; scalePack: string; accountCredit: string; paygCredit: string; includesBonus: string; bonusCredit: string; consoleTitle: string; consoleLead: string; finalTitle: string; finalLead: string; getStarted: string };
  models: { kicker: string; title: string; lead: string; search: string; all: string; coding: string; reasoning: string; general: string; multilingual: string; noResults: string; clearFilters: string; unavailable: string; available: string; enabled: string; context: string; speed: string; fast: string; balanced: string; deep: string; input: string; output: string; tools: string; modelId: string; availability: string; details: string };
  pricing: { kicker: string; title: string; lead: string; demoNotice: string; calculator: string; selectModel: string; inputTokens: string; outputTokens: string; estimate: string; invalid: string; ratesTitle: string };
  docs: { kicker: string; title: string; lead: string; quickStart: string; baseUrl: string; apiKey: string; chooseModel: string; curl: string; python: string; javascript: string; copy: string; copied: string };
  console: { demo: string; title: string; balance: string; sevenDay: string; tokens: string; illustrativeSpend: string; modelSplit: string; recent: string; apiKey: string; copy: string; copied: string; noUsage: string; noRecent: string };
  checkout: { title: string; choose: string; review: string; complete: string; back: string; next: string; close: string; demoOnly: string; launchNotice: string; requestComplete: string };
  footer: { label: string; navigation: string; about: string; status: string; terms: string; privacy: string };
  shared: { perMillionInput: string; perMillionOutput: string; illustrative: string; temporarilyUnavailable: string; language: string; copyUnavailable: string };
};

export const COPY: Record<Locale, CopyDictionary> = {
  en: {
    nav: { models: "Models", pricing: "Pricing", docs: "Docs", company: "Company", console: "Console", getTokens: "Join launch access", openMenu: "Open menu", closeMenu: "Close menu", skipToContent: "Skip to main content", primaryLabel: "Primary navigation", mobileLabel: "Mobile navigation" },
    home: { kicker: "The open model power layer", title: "Every model.", accent: "One power core.", lead: "Build, test, and scale with leading open AI models through one clean endpoint and infrastructure engineered for momentum.", launchStatus: "Token access launching soon", explore: "Explore the marketplace", viewPricing: "View pricing", proofLabel: "Marketplace proof points", activeRoutes: "active model routes", contextAvailable: "context available", illustrativeAvailability: "illustrative availability", modelsTitle: "Route every task to the right mind.", modelsLead: "One engineered layer for coding, reasoning, multilingual work, and production workloads.", startingInputRate: "Illustrative starting input rate", creditTitle: "Explore indicative launch packages.", creditLead: "Review indicative package examples before requesting non-binding launch access.", starterPack: "Starter", builderPack: "Builder", scalePack: "Scale", accountCredit: "indicative account credit", paygCredit: "Indicative launch package", includesBonus: "Includes", bonusCredit: "indicative launch bonus", consoleTitle: "Your power, clearly accounted for.", consoleLead: "Large totals and restrained usage signals keep the important information clear.", finalTitle: "Put intelligence in motion.", finalLead: "One API. One balance. Every open model powered by one core.", getStarted: "Get started" },
    models: { kicker: "Model marketplace", title: "Choose the mind for the task.", lead: "Compare open model families without switching providers.", search: "Search models", all: "All", coding: "Coding", reasoning: "Reasoning", general: "General", multilingual: "Multilingual", noResults: "No models match this search. Clear the query or choose another category.", clearFilters: "Clear filters", unavailable: "Temporarily unavailable", available: "Available", enabled: "Enabled", context: "Context", speed: "Speed", fast: "Fast", balanced: "Balanced", deep: "Deep", input: "Input", output: "Output", tools: "Tool use", modelId: "Model ID", availability: "Availability", details: "details" },
    pricing: { kicker: "Illustrative pricing", title: "Indicative packages. No commitment.", lead: "Review illustrative package examples and model rates before requesting launch access.", demoNotice: "Illustrative package values only — requests are local to this demonstration and do not create orders, charges, or reservations.", calculator: "Estimate usage", selectModel: "Select a model", inputTokens: "Input tokens", outputTokens: "Output tokens", estimate: "Estimated cost", invalid: "Enter non-negative token amounts.", ratesTitle: "Model rates" },
    docs: { kicker: "Quick start", title: "One endpoint. Familiar tools.", lead: "Use the OpenAI-compatible format your application already understands.", quickStart: "Quick start", baseUrl: "Base URL", apiKey: "Demo API key", chooseModel: "Choose a model", curl: "cURL", python: "Python", javascript: "JavaScript", copy: "Copy", copied: "Copied" },
    console: { demo: "Demo console", title: "Usage without the noise.", balance: "Available balance", sevenDay: "Seven-day usage", tokens: "tokens", illustrativeSpend: "Illustrative spend", modelSplit: "Model split", recent: "Recent requests", apiKey: "Demo API key", copy: "Copy", copied: "Copied", noUsage: "No usage yet. Your first demo request will appear here.", noRecent: "No recent requests yet. Demo requests will appear here." },
    checkout: { title: "Request launch access", choose: "Choose an indicative package", review: "Review your request", complete: "Launch access request saved locally.", back: "Back", next: "Continue", close: "Close", demoOnly: "Payments are not enabled yet. This request does not create an order or charge your account.", launchNotice: "Payments are not enabled yet. This request does not create an order or charge your account.", requestComplete: "This request is local to this demonstration and does not reserve capacity." },
    footer: { label: "Footer", navigation: "Footer navigation", about: "About", status: "Status", terms: "Terms", privacy: "Privacy" },
    shared: { perMillionInput: "per 1M input", perMillionOutput: "per 1M output", illustrative: "Illustrative data", temporarilyUnavailable: "Temporarily unavailable", language: "Language", copyUnavailable: "Copy unavailable" },
  },
  zh: {
    nav: { models: "模型", pricing: "價格", docs: "文件", company: "公司", console: "控制台", getTokens: "加入啟動存取", openMenu: "開啟選單", closeMenu: "關閉選單", skipToContent: "跳至主要內容", primaryLabel: "主要導覽", mobileLabel: "行動版導覽" },
    home: { kicker: "開源模型運算核心", title: "所有模型，", accent: "共享一個核心。", lead: "透過單一端點與專為成長打造的基礎設施，建置、測試並擴展領先的開源 AI 模型。", launchStatus: "Token 存取即將推出", explore: "探索模型市集", viewPricing: "查看價格", proofLabel: "市集成效數據", activeRoutes: "啟用中的模型路由", contextAvailable: "可用上下文", illustrativeAvailability: "展示可用率", modelsTitle: "讓每項任務使用最適合的模型。", modelsLead: "一套工程化服務層，涵蓋程式開發、推理、多語言與正式工作負載。", startingInputRate: "展示起始輸入費率", creditTitle: "探索指示性啟動方案。", creditLead: "先查看指示性方案範例，再提出無約束力的啟動存取請求。", starterPack: "入門", builderPack: "建置", scalePack: "規模", accountCredit: "指示性帳戶額度", paygCredit: "指示性啟動方案", includesBonus: "包含", bonusCredit: "指示性啟動加碼", consoleTitle: "每一份算力，都清楚可見。", consoleLead: "大型總額與克制的用量訊號，讓重要資訊保持清楚。", finalTitle: "讓智慧開始運轉。", finalLead: "一套 API、一個餘額，所有開源模型由同一核心驅動。", getStarted: "開始使用" },
    models: { kicker: "模型市集", title: "為任務選擇正確的智慧。", lead: "無需切換供應商，就能比較各類開源模型。", search: "搜尋模型", all: "全部", coding: "程式開發", reasoning: "推理", general: "通用", multilingual: "多語言", noResults: "找不到符合條件的模型。請清除搜尋或選擇其他分類。", clearFilters: "清除篩選", unavailable: "暫時無法使用", available: "可用", enabled: "已啟用", context: "上下文", speed: "速度", fast: "快速", balanced: "均衡", deep: "深度", input: "輸入", output: "輸出", tools: "工具呼叫", modelId: "模型 ID", availability: "可用性", details: "詳細資料" },
    pricing: { kicker: "展示價格", title: "指示性方案，無需承諾。", lead: "查看展示方案範例與模型費率，再提出啟動存取請求。", demoNotice: "方案數值僅供展示；請求只會儲存在此展示中，不會建立訂單、收費或保留名額。", calculator: "估算用量", selectModel: "選擇模型", inputTokens: "輸入 Token", outputTokens: "輸出 Token", estimate: "預估費用", invalid: "請輸入非負數的 Token 數量。", ratesTitle: "模型費率" },
    docs: { kicker: "快速開始", title: "一個端點，熟悉的工具。", lead: "沿用應用程式已熟悉的 OpenAI 相容格式。", quickStart: "快速開始", baseUrl: "基礎 URL", apiKey: "展示 API Key", chooseModel: "選擇模型", curl: "cURL", python: "Python", javascript: "JavaScript", copy: "複製", copied: "已複製" },
    console: { demo: "展示控制台", title: "清楚用量，不被雜訊干擾。", balance: "可用餘額", sevenDay: "七日用量", tokens: "詞元", illustrativeSpend: "展示支出", modelSplit: "模型分布", recent: "近期請求", apiKey: "展示 API Key", copy: "複製", copied: "已複製", noUsage: "目前尚無用量，第一筆展示請求會顯示在這裡。", noRecent: "目前尚無近期請求，展示請求會顯示在這裡。" },
    checkout: { title: "申請啟動存取", choose: "選擇指示性方案", review: "確認您的請求", complete: "啟動存取請求已儲存在本機。", back: "返回", next: "繼續", close: "關閉", demoOnly: "付款功能尚未啟用。此請求不會建立訂單，也不會向您的帳戶收費。", launchNotice: "付款功能尚未啟用。此請求不會建立訂單，也不會向您的帳戶收費。", requestComplete: "此請求僅儲存在本展示中，且不會保留名額。" },
    footer: { label: "頁尾", navigation: "頁尾導覽", about: "關於", status: "服務狀態", terms: "使用條款", privacy: "隱私權" },
    shared: { perMillionInput: "每百萬輸入 Token", perMillionOutput: "每百萬輸出 Token", illustrative: "展示資料", temporarilyUnavailable: "暫時無法使用", language: "語言", copyUnavailable: "無法複製" },
  },
};
