import type { InternationalLanguage } from "./languages";

export type HomeLanguage = InternationalLanguage | "en";
export type HomeCategory =
  "featured" | "text" | "vision" | "creative" | "retrieval";

const EN = {
  categories: {
    featured: "Featured models",
    text: "Text & reasoning",
    vision: "Vision",
    creative: "Image & audio",
    retrieval: "Search & retrieval",
  } as Record<HomeCategory, string>,
  cardCategories: {
    image: "IMAGE GENERATION",
    audio: "SPEECH & AUDIO",
    embedding: "SEARCH & RETRIEVAL",
    vision: "VISION & LANGUAGE",
    text: "TEXT & REASONING",
  },
  units: {
    image: "/ image",
    audio: "/ audio min",
    tokens: "/ 1M input tokens",
  },
  modelFamilies: "Model families",
  familiesStatement: "A world of intelligence.\nOne curated collection.",
  platformTools: "Platform tools",
  openPlatform: "Open the platform",
  platformDescription: "Explore. Compare. Test. Connect.",
  compareModels: "Compare models & costs",
  playground: "Try the playground",
  connectApp: "Connect your app",
  workspaceNote:
    "Interactive developer tools, model details, and documentation are available in English and Traditional Chinese.",
  modelOverline: "THE MODEL COLLECTION",
  modelTitle: ["Great ideas deserve", "the right intelligence."],
  modelLead:
    "Sharper conversations. Richer creations. Find the model that fits your product, all through a familiar API.",
  allModels: "Explore all {count} models",
  filterModels: "Filter models",
  modelRates: "Rates in USD. See pricing for full input and output rates.",
  checkStatus: "Check service availability",
  explore: "Explore",
  devOverline: "MADE FOR DEVELOPERS",
  devTitle: ["Less setup.", "More building."],
  devLead:
    "Bring your code. Pick your model. A familiar SDK and straightforward docs let you focus on the experience you're creating.",
  devSteps: [
    "Request your API key",
    "Set your base URL",
    "Choose a model. Start building.",
  ],
  docs: "Explore documentation",
  codeLanguage: "Code language",
  copyCode: "Copy code",
  copied: "Copied ✓",
  codeExample: "integration example",
  copyError: "Copy unavailable. Select and copy the code above.",
  keyNote: "Use your own API key. Check status for model availability.",
  copySuccess: "Code copied to clipboard",
  samplePrompt: "Let us build something extraordinary.",
  infraOverline: "BEYOND THE API",
  infraTitle: ["Bigger ambitions.", "Deeper power."],
  infraLead:
    "For workloads that need their own foundation. Explore NVIDIA HGX-based GPU infrastructure, from dedicated B300 compute to custom model deployments.",
  dedicated: "Dedicated compute",
  custom: "Custom deployment",
  exploreInfrastructure: "Explore GPU infrastructure",
  infraNote:
    "Configuration, capacity, and delivery are scoped to your project.",
  infraVisual: "Conceptual dedicated GPU cluster illustration",
  computeLabel: "POWER CHAMPION / COMPUTE",
  computeName: "GPU COMPUTE",
  rackCaption: "ENGINEERED FOR DEMANDING AI",
  companyOverline: "THE PEOPLE BEHIND THE POWER",
  companyTitle: ["Your next chapter.", "Our shared ambition."],
  companyLead:
    "Power Champion connects model services with AI infrastructure, helping developers and enterprises move from experimentation toward real-world applications.",
  meet: "Meet Power Champion",
  project: "Talk about your project",
  taipei: "TAIPEI, TAIWAN",
  location: "CONNECTED TO WHAT'S NEXT",
  faqOverline: "A FEW THINGS TO KNOW",
  faqTitle: "Before you build.",
  moreFaq: "More answers",
  faqs: [
    [
      "What can I build with Power Champion?",
      "Build with model APIs for reasoning, vision, image generation, speech, and retrieval. For workloads that need dedicated resources, we also offer enterprise GPU infrastructure and custom deployment planning.",
    ],
    [
      "Can I use my existing OpenAI SDK?",
      "Yes. Compatible endpoints work with the OpenAI SDK. Set your base URL to https://b300.powerchampion.ai/v1 and use your Power Champion API key and a supported model ID. Check the documentation for each model's supported capabilities.",
    ],
    [
      "How does model pricing work?",
      "Use a prepaid balance and pay for usage. Text and retrieval use token-based rates, images are billed per image, and audio is billed per minute. See the pricing page for full rates and top-up options.",
    ],
    [
      "Do you offer dedicated GPU infrastructure?",
      "Yes. Talk to us about dedicated GPU clusters, single-tenant infrastructure, and custom model deployments. Hardware, location, capacity, and service terms are confirmed for your workload.",
    ],
  ],
  ctaOverline: "YOUR NEXT POSSIBILITY STARTS HERE",
  ctaTitle: ["Let’s build", "what’s next."],
  access: "Get API access",
  talk: "Talk to our team",
};

export type HomeCopy = typeof EN;
export const HOME_COPY: Record<HomeLanguage, HomeCopy> = {
  en: EN,
  "zh-Hant": {
    categories: {
      featured: "精選模型",
      text: "文字與推理",
      vision: "視覺理解",
      creative: "圖像與音訊",
      retrieval: "搜尋與檢索",
    },
    cardCategories: {
      image: "圖像生成",
      audio: "語音與音訊",
      embedding: "搜尋與檢索",
      vision: "視覺理解",
      text: "文字與推理",
    },
    units: {
      image: "／張圖片",
      audio: "／音訊分鐘",
      tokens: "／百萬輸入 Token",
    },
    modelFamilies: "模型家族",
    familiesStatement: "精選開放模型\n激發更多可能",
    platformTools: "平台工具",
    openPlatform: "進入模型平台",
    platformDescription: "探索、比較、測試、串接",
    compareModels: "比較模型與費用",
    playground: "測試模型 API",
    connectApp: "設定產品串接",
    workspaceNote: "互動開發工具、模型詳情及技術文件提供英文與繁體中文。",
    modelOverline: "模型服務",
    modelTitle: ["每個想法，", "都有合適的模型。"],
    modelLead:
      "從更聰明的對話到更出色的創作，依你的產品挑選模型，用熟悉的 API 串起一切。",
    allModels: "查看全部 {count} 個模型",
    filterModels: "篩選模型",
    modelRates: "以美元計價。完整輸入／輸出費率請見價格頁。",
    checkStatus: "查看即時服務狀態",
    explore: "查看",
    devOverline: "為開發者而生",
    devTitle: ["少一點設定。", "多一點創造。"],
    devLead:
      "帶上你的程式碼，選擇合適的模型。熟悉的 SDK、清楚的文件，讓你把心力放在真正重要的產品體驗。",
    devSteps: ["申請 API 金鑰", "設定相容端點", "選擇模型，開始打造"],
    docs: "查看開發文件",
    codeLanguage: "程式碼語言",
    copyCode: "複製程式碼",
    copied: "已複製 ✓",
    codeExample: "整合範例",
    copyError: "無法自動複製，請選取上方程式碼複製。",
    keyNote: "需使用有效金鑰；模型可用狀態請見服務狀態頁。",
    copySuccess: "程式碼已複製",
    samplePrompt: "一起打造出色的產品。",
    infraOverline: "企業算力服務",
    infraTitle: ["更大的企圖心。", "更深一層的算力。"],
    infraLead:
      "模型服務之外，我們也提供以 NVIDIA HGX 為基礎的 GPU 叢集規劃。從 B300 專用算力到客製部署，讓基礎設施配合你的工作負載。",
    dedicated: "專用算力",
    custom: "客製部署",
    exploreInfrastructure: "探索算力服務",
    infraNote: "配置、容量與交付條件依專案確認。",
    infraVisual: "專用 GPU 叢集概念圖",
    computeLabel: "POWER CHAMPION / 算力",
    computeName: "GPU 算力",
    rackCaption: "為高強度 AI 工作負載而設計",
    companyOverline: "認識 POWER CHAMPION",
    companyTitle: ["你的下一步，", "我們一起打造。"],
    companyLead:
      "Power Champion 連結模型服務與 AI 基礎設施，陪伴開發者與企業，把實驗中的想法推進到實際應用。",
    meet: "認識我們",
    project: "討論你的專案",
    taipei: "台灣・台北",
    location: "與全球開發者連結",
    faqOverline: "常見問題",
    faqTitle: "開始之前。",
    moreFaq: "更多常見問題",
    faqs: [
      [
        "Power Champion 提供哪些服務？",
        "我們以模型 API 服務為核心，提供文字推理、視覺理解、圖像生成、語音及檢索模型；同時提供 B300 等企業 GPU 算力與專用部署規劃。",
      ],
      [
        "可以使用既有的 OpenAI SDK 嗎？",
        "可以。相容端點可使用 OpenAI SDK，將 Base URL 改為 https://b300.powerchampion.ai/v1，並使用 Power Champion 的 API 金鑰與支援的模型 ID。各模型支援的功能請參考文件。",
      ],
      [
        "模型服務如何計費？",
        "採預付餘額、按使用量扣款。文字與檢索依 Token 計費，圖像依張數、音訊依分鐘計費；完整費率與儲值方式可在價格頁查看。",
      ],
      [
        "能否使用專屬 GPU 或客製部署？",
        "可以洽詢專用 GPU 叢集、單一租戶及客製模型部署。硬體、地點、容量與服務條件會依工作負載個別確認。",
      ],
    ],
    ctaOverline: "下一個可能，由你開始",
    ctaTitle: ["準備好，", "打造下一個突破。"],
    access: "取得 API 存取",
    talk: "與我們聊聊",
  },
  "zh-Hans": {
    categories: {
      featured: "精选模型",
      text: "文本与推理",
      vision: "视觉理解",
      creative: "图像与音频",
      retrieval: "搜索与检索",
    },
    cardCategories: {
      image: "图像生成",
      audio: "语音与音频",
      embedding: "搜索与检索",
      vision: "视觉理解",
      text: "文本与推理",
    },
    units: {
      image: "／张图片",
      audio: "／音频分钟",
      tokens: "／百万输入 Token",
    },
    modelFamilies: "模型系列",
    familiesStatement: "精选开放模型\n激发更多可能",
    platformTools: "平台工具",
    openPlatform: "进入模型平台",
    platformDescription: "探索、比较、测试、接入",
    compareModels: "比较模型与费用",
    playground: "测试模型 API",
    connectApp: "配置应用接入",
    workspaceNote: "交互式开发工具、模型详情及技术文档提供英语与繁体中文。",
    modelOverline: "模型服务",
    modelTitle: ["每个想法，", "都有合适的模型。"],
    modelLead:
      "从更智能的对话到更出色的创作，为你的产品挑选模型，用熟悉的 API 连接各个环节。",
    allModels: "查看全部 {count} 个模型",
    filterModels: "筛选模型",
    modelRates: "以美元计价。完整输入／输出费率请查看价格页。",
    checkStatus: "查看实时服务状态",
    explore: "查看",
    devOverline: "为开发者而生",
    devTitle: ["少一点配置。", "多一点创造。"],
    devLead:
      "带上你的代码，选择合适的模型。熟悉的 SDK、清晰的文档，让你把精力放在产品体验上。",
    devSteps: ["申请 API 密钥", "设置兼容端点", "选择模型，开始构建"],
    docs: "查看开发文档",
    codeLanguage: "代码语言",
    copyCode: "复制代码",
    copied: "已复制 ✓",
    codeExample: "接入示例",
    copyError: "无法自动复制，请选取上方代码手动复制。",
    keyNote: "请使用有效密钥；模型可用性请查看服务状态页。",
    copySuccess: "代码已复制",
    samplePrompt: "一起打造出色的产品。",
    infraOverline: "企业算力服务",
    infraTitle: ["更大的目标。", "更深一层的算力。"],
    infraLead:
      "模型服务之外，我们也提供基于 NVIDIA HGX 的 GPU 集群规划。从 B300 专用算力到定制部署，让基础设施配合你的工作负载。",
    dedicated: "专用算力",
    custom: "定制部署",
    exploreInfrastructure: "探索算力服务",
    infraNote: "配置、容量与交付条件按项目确认。",
    infraVisual: "专用 GPU 集群概念图",
    computeLabel: "POWER CHAMPION / 算力",
    computeName: "GPU 算力",
    rackCaption: "为高强度 AI 工作负载而设计",
    companyOverline: "认识 POWER CHAMPION",
    companyTitle: ["你的下一步，", "我们一起打造。"],
    companyLead:
      "Power Champion 连接模型服务与 AI 基础设施，帮助开发者与企业把实验中的想法推进到实际应用。",
    meet: "认识我们",
    project: "讨论你的项目",
    taipei: "台湾・台北",
    location: "连接全球开发者",
    faqOverline: "常见问题",
    faqTitle: "开始之前。",
    moreFaq: "更多常见问题",
    faqs: [
      [
        "Power Champion 提供哪些服务？",
        "我们以模型 API 为核心，提供文本推理、视觉理解、图像生成、语音及检索模型；同时提供 B300 等企业 GPU 算力与专用部署规划。",
      ],
      [
        "可以使用现有的 OpenAI SDK 吗？",
        "可以。兼容端点支持 OpenAI SDK，将 Base URL 改为 https://b300.powerchampion.ai/v1，并使用 Power Champion 的 API 密钥与支持的模型 ID。各模型支持的功能请参考文档。",
      ],
      [
        "模型服务如何计费？",
        "采用预付余额，按使用量扣费。文本与检索按 Token 计费，图像按张数、音频按分钟计费；完整费率与充值方式可在价格页查看。",
      ],
      [
        "能否使用专属 GPU 或定制部署？",
        "可以咨询专用 GPU 集群、单租户与定制模型部署。硬件、地点、容量与服务条件将按工作负载分别确认。",
      ],
    ],
    ctaOverline: "下一个可能，由你开始",
    ctaTitle: ["准备好，", "打造下一个突破。"],
    access: "获取 API 访问权限",
    talk: "与我们聊聊",
  },
  ja: {
    categories: {
      featured: "注目のモデル",
      text: "テキスト・推論",
      vision: "画像理解",
      creative: "画像・音声",
      retrieval: "検索・取得",
    },
    cardCategories: {
      image: "画像生成",
      audio: "音声処理",
      embedding: "検索・情報取得",
      vision: "画像と言語の理解",
      text: "テキスト・推論",
    },
    units: {
      image: "／画像 1 枚",
      audio: "／音声 1 分",
      tokens: "／100 万入力トークン",
    },
    modelFamilies: "モデルファミリー",
    familiesStatement: "多様な知能を、\nひとつのコレクションに。",
    platformTools: "プラットフォームのツール",
    openPlatform: "プラットフォームを開く",
    platformDescription: "探す。比べる。試す。つなぐ。",
    compareModels: "モデルと費用を比較",
    playground: "API を試す",
    connectApp: "アプリに接続",
    workspaceNote:
      "開発ツール、モデル詳細、技術ドキュメントは英語と繁体字中国語で提供しています。",
    modelOverline: "モデルコレクション",
    modelTitle: ["そのアイデアに、", "合う知能を。"],
    modelLead:
      "会話を深め、創作を広げる。製品に合うモデルを選び、使い慣れた API でつなげます。",
    allModels: "全 {count} モデルを見る",
    filterModels: "モデルを絞り込む",
    modelRates:
      "料金は米ドル建てです。入力・出力の全料金は料金ページをご覧ください。",
    checkStatus: "サービス状況を確認",
    explore: "詳細を見る",
    devOverline: "開発者のために",
    devTitle: ["設定をシンプルに。", "創ることに集中。"],
    devLead:
      "コードを用意し、モデルを選ぶ。使い慣れた SDK とわかりやすいドキュメントで、製品の体験づくりに集中できます。",
    devSteps: [
      "API キーを申請",
      "接続先 URL を設定",
      "モデルを選んで開発を開始",
    ],
    docs: "開発ドキュメントを見る",
    codeLanguage: "コードの言語",
    copyCode: "コードをコピー",
    copied: "コピー済み ✓",
    codeExample: "接続例",
    copyError:
      "コピーできません。上のコードを選択して手動でコピーしてください。",
    keyNote:
      "ご自身の有効な API キーを使用し、モデルの稼働状況をご確認ください。",
    copySuccess: "コードをコピーしました",
    samplePrompt: "一緒に優れた製品を作りましょう。",
    infraOverline: "API の、その先へ",
    infraTitle: ["大きな構想に。", "確かな計算基盤を。"],
    infraLead:
      "独自の基盤が必要なワークロードへ。専用 B300 から個別モデルの導入まで、NVIDIA HGX を基盤とする GPU インフラを検討できます。",
    dedicated: "専用コンピュート",
    custom: "個別導入",
    exploreInfrastructure: "GPU インフラを見る",
    infraNote: "構成、容量、提供条件はプロジェクトごとに確認します。",
    infraVisual: "専用 GPU クラスタの概念図",
    computeLabel: "POWER CHAMPION / 計算基盤",
    computeName: "GPU 計算基盤",
    rackCaption: "負荷の高い AI 処理を支える設計",
    companyOverline: "POWER CHAMPION について",
    companyTitle: ["次の挑戦を、", "ともに形に。"],
    companyLead:
      "Power Champion はモデルサービスと AI インフラを結び、開発者や企業が実験から実際のアプリケーションへ進む道筋を支えます。",
    meet: "Power Champion を知る",
    project: "プロジェクトを相談",
    taipei: "台湾・台北",
    location: "世界の開発者とつながる",
    faqOverline: "よくある質問",
    faqTitle: "開発を始める前に。",
    moreFaq: "その他の質問",
    faqs: [
      [
        "Power Champion で何を作れますか？",
        "推論、画像理解、画像生成、音声、情報検索のモデル API を利用できます。専用リソースが必要な場合は、企業向け GPU インフラや個別導入の計画もご相談いただけます。",
      ],
      [
        "既存の OpenAI SDK を使えますか？",
        "はい。対応するエンドポイントは OpenAI SDK で利用できます。Base URL を https://b300.powerchampion.ai/v1 に変更し、Power Champion の API キーと対応モデル ID を設定してください。各モデルの対応機能はドキュメントをご確認ください。",
      ],
      [
        "モデルの料金はどのように計算されますか？",
        "プリペイド残高から使用量に応じて課金されます。テキストと検索はトークン単位、画像は枚数、音声は分単位です。全料金とチャージ方法は料金ページをご覧ください。",
      ],
      [
        "専用 GPU や個別の導入に対応していますか？",
        "専用 GPU クラスタ、シングルテナント環境、個別モデルの導入をご相談いただけます。ハードウェア、場所、容量、サービス条件はワークロードに合わせて確認します。",
      ],
    ],
    ctaOverline: "次の可能性は、ここから",
    ctaTitle: ["ともに作ろう。", "その次の一歩を。"],
    access: "API の利用を相談",
    talk: "チームに相談",
  },
  ko: {
    categories: {
      featured: "추천 모델",
      text: "텍스트·추론",
      vision: "이미지 이해",
      creative: "이미지·음성",
      retrieval: "검색·정보 탐색",
    },
    cardCategories: {
      image: "이미지 생성",
      audio: "음성 처리",
      embedding: "검색·정보 탐색",
      vision: "이미지·언어 이해",
      text: "텍스트·추론",
    },
    units: {
      image: "／이미지 1장",
      audio: "／음성 1분",
      tokens: "／입력 100만 토큰",
    },
    modelFamilies: "모델 제품군",
    familiesStatement: "다양한 지능을,\n하나의 컬렉션에서.",
    platformTools: "플랫폼 도구",
    openPlatform: "플랫폼 열기",
    platformDescription: "탐색. 비교. 테스트. 연결.",
    compareModels: "모델·비용 비교",
    playground: "API 테스트",
    connectApp: "앱에 연결",
    workspaceNote:
      "개발 도구, 모델 상세, 기술 문서는 영어와 번체 중국어로 제공됩니다.",
    modelOverline: "모델 컬렉션",
    modelTitle: ["좋은 아이디어에,", "알맞은 지능을."],
    modelLead:
      "더 깊은 대화, 더 풍부한 창작. 제품에 맞는 모델을 선택하고 익숙한 API로 연결하세요.",
    allModels: "전체 {count}개 모델 보기",
    filterModels: "모델 필터",
    modelRates:
      "요금은 미국 달러 기준입니다. 전체 입력·출력 요금은 요금 페이지를 확인하세요.",
    checkStatus: "서비스 상태 확인",
    explore: "자세히 보기",
    devOverline: "개발자를 위한 설계",
    devTitle: ["설정은 간단하게.", "개발에 집중하세요."],
    devLead:
      "코드를 준비하고 모델을 선택하세요. 익숙한 SDK와 명확한 문서로 제품 경험을 만드는 데 집중할 수 있습니다.",
    devSteps: ["API 키 신청", "기본 URL 설정", "모델을 선택하고 개발 시작"],
    docs: "개발 문서 보기",
    codeLanguage: "코드 언어",
    copyCode: "코드 복사",
    copied: "복사됨 ✓",
    codeExample: "연동 예제",
    copyError: "자동으로 복사할 수 없습니다. 위 코드를 선택해 직접 복사하세요.",
    keyNote: "본인의 유효한 API 키를 사용하고 모델 서비스 상태를 확인하세요.",
    copySuccess: "코드를 복사했습니다",
    samplePrompt: "함께 좋은 제품을 만들어 봅시다.",
    infraOverline: "API를 넘어",
    infraTitle: ["더 큰 목표에,", "더 깊은 컴퓨팅 기반을."],
    infraLead:
      "독립된 기반이 필요한 워크로드를 위해 전용 B300부터 맞춤형 모델 구축까지 NVIDIA HGX 기반 GPU 인프라를 검토하세요.",
    dedicated: "전용 컴퓨팅",
    custom: "맞춤 구축",
    exploreInfrastructure: "GPU 인프라 살펴보기",
    infraNote: "구성, 용량, 제공 조건은 프로젝트별로 확인합니다.",
    infraVisual: "전용 GPU 클러스터 개념도",
    computeLabel: "POWER CHAMPION / 컴퓨팅",
    computeName: "GPU 컴퓨팅",
    rackCaption: "높은 부하의 AI 작업을 위한 설계",
    companyOverline: "POWER CHAMPION 소개",
    companyTitle: ["다음 도전을,", "함께 현실로."],
    companyLead:
      "Power Champion은 모델 서비스와 AI 인프라를 연결해 개발자와 기업이 실험에서 실제 애플리케이션으로 나아가도록 지원합니다.",
    meet: "Power Champion 알아보기",
    project: "프로젝트 상담",
    taipei: "대만·타이베이",
    location: "전 세계 개발자와 연결",
    faqOverline: "자주 묻는 질문",
    faqTitle: "개발을 시작하기 전에.",
    moreFaq: "더 많은 답변",
    faqs: [
      [
        "Power Champion으로 무엇을 만들 수 있나요?",
        "추론, 이미지 이해, 이미지 생성, 음성, 검색 모델 API를 활용할 수 있습니다. 전용 자원이 필요한 작업에는 기업용 GPU 인프라와 맞춤 구축 계획도 지원합니다.",
      ],
      [
        "기존 OpenAI SDK를 사용할 수 있나요?",
        "네. 호환 엔드포인트는 OpenAI SDK를 지원합니다. Base URL을 https://b300.powerchampion.ai/v1로 설정하고 Power Champion API 키와 지원 모델 ID를 사용하세요. 모델별 기능은 문서에서 확인하세요.",
      ],
      [
        "모델 요금은 어떻게 계산하나요?",
        "선불 잔액에서 사용량에 따라 차감됩니다. 텍스트와 검색은 토큰 단위, 이미지는 장수, 음성은 분 단위로 과금됩니다. 전체 요금과 충전 방법은 요금 페이지를 확인하세요.",
      ],
      [
        "전용 GPU와 맞춤 구축도 제공하나요?",
        "전용 GPU 클러스터, 단일 고객 전용 환경, 맞춤형 모델 구축을 상담할 수 있습니다. 하드웨어, 위치, 용량, 서비스 조건은 워크로드에 따라 확인합니다.",
      ],
    ],
    ctaOverline: "다음 가능성은 여기에서",
    ctaTitle: ["함께 만들어갈", "다음 가능성."],
    access: "API 이용 문의",
    talk: "팀에 문의",
  },
};
