export const PLAYGROUND_TEXT = {
  en: {
    eyebrow: "DEVELOPER WORKSPACE",
    title: "Playground",
    lead: "Try a prompt. Inspect the response. Take it into your application.",
    protocol: "TEXT / SINGLE TURN",
    steps: ["Choose a model", "Add your API key", "Write a prompt"],
    advanced: "Advanced settings",
    advancedNote: "Instructions & output limit",
    examplesTitle: "Start with a use case",
    examplesNote: "Loads a prompt. Nothing is sent.",
    presets: [
      { id: "plan", icon: "↗", title: "Compare trade-offs", detail: "Turn constraints into a decision.", prompt: "We are building a customer support assistant for a 12-person team. Compare a managed model API with self-hosting an open model. We need to launch in six weeks, handle private company documents, and keep operations simple. Give a concise decision matrix, state your assumptions, and suggest what we should validate before choosing." },
      { id: "code", icon: "⌘", title: "Review code", detail: "Find a bug. Explain a repair.", prompt: "Review this JavaScript function for correctness. Explain the bug, provide a corrected version, and suggest one test that would have caught it.\n\nasync function loadUsers(ids) {\n  const users = [];\n  ids.forEach(async (id) => {\n    const response = await fetch('/users/' + id);\n    users.push(await response.json());\n  });\n  return users;\n}" },
      { id: "extract", icon: "{ }", title: "Extract structured data", detail: "Give unstructured notes a schema.", prompt: "Extract the following fictional project note into valid JSON only. Use keys project, owner, deadline, decisions (array), and open_questions (array). Use null for any missing value; do not invent details.\n\nProject Atlas: The design team owns the prototype. Target delivery is 2026-10-15. We agreed to support English and Traditional Chinese at launch. Mobile layout is required. Hosting and the final budget are still undecided." },
    ],
    needsKey: "Add an API key to continue",
    invalidKey: "Check your API key format",
    needsPrompt: "Write a prompt to continue",
    invalidTokens: "Check the output token limit",
    canSend: "Ready to send",
    characters: "characters",
    copyResponse: "Copy response",
    responseCopied: "Response copied",
    responseCopyFailed: "Select the response to copy it manually.",
    requestTime: "Request time",
    codeLanguages: "Code language",
    runtimes: { curl: "Terminal · cURL", python: "Python 3 · standard library", javascript: "Node.js · save as .mjs" },
    setup: "Request settings",
    model: "Model",
    textOnly:
      "Text requests only. For vision, image and audio inputs, use the API documentation.",
    key: "API key",
    keyPlaceholder: "Enter your PowerChampion API key",
    keyNote:
      "Your key stays in this page’s memory and is forwarded only to the PowerChampion gateway for your request. It is not saved by this workbench.",
    clearKey: "Clear key",
    getKey: "Get API access",
    status: "Check service status",
    system: "System instructions",
    optional: "Optional",
    systemPlaceholder:
      "You are a helpful assistant. Keep your answers clear and concise.",
    tokens: "Maximum output tokens",
    tokensNote: "1–4,096 tokens. Actual usage depends on the model response.",
    prompt: "Your prompt",
    promptPlaceholder: "What would you like to explore?",
    singleTurn: "Single-turn request",
    example: "Use an example",
    examplePrompt:
      "Explain how an API works in two sentences, then give one practical example for a small business.",
    send: "Send API request",
    sending: "Waiting for response…",
    cancel: "Cancel request",
    billed:
      "Requests use your API credits and may be billed, including requests you cancel or that time out.",
    result: "Response",
    ready: "Ready when you are",
    empty:
      "Choose a model, enter your key and send a prompt. The actual model response will appear here.",
    waiting: "Your request is running on the selected model.",
    waitingNote:
      "A response may take up to 45 seconds. You can cancel at any time.",
    input: "Input tokens",
    output: "Output tokens",
    total: "Total tokens",
    unavailable: "Not reported",
    usageNote:
      "Token counts are reported by the gateway. Check your balance for billing information.",
    balance: "View balance",
    reasoning: "Model reasoning",
    noContent:
      "The model returned reasoning without a final answer. Try increasing the output token limit.",
    truncated:
      "The response reached the output token limit. Increase the limit for a longer response.",
    filtered: "The model marked this response as filtered.",
    code: "Request code",
    copy: "Copy code",
    copied: "Copied",
    copyFailed: "Copy is unavailable. Select the code to copy it manually.",
    codeNote:
      "Set POWERCHAMPION_API_KEY in your environment. This example reflects the settings above and excludes your key.",
    docs: "Read the API docs",
    cancelled: "Request cancelled. Gateway usage may still be billed.",
    errors: {
      authentication:
        "Please check that your API key is valid and has access to this model.",
      credits:
        "Your key has insufficient credits. Check your balance or contact support to top up.",
      rate_limit:
        "The gateway is limiting requests. Wait a moment before trying again.",
      timeout:
        "The request timed out. Check service status before retrying; usage may still be billed.",
      input:
        "Check your key, prompt and output token limit before sending again.",
      too_large:
        "Your request is too large. Shorten your prompt and system instructions.",
      origin:
        "This request could not be verified. Refresh the page and try again.",
      response:
        "The gateway did not return a usable text response. Check service status or try another model.",
      gateway:
        "The model gateway is unavailable or could not complete the request. Check service status before trying again.",
      network:
        "The request could not reach the gateway. Check your connection and service status; avoid repeated retries.",
    },
  },
  zh: {
    eyebrow: "開發者工作區",
    title: "模型測試台",
    lead: "測試提示詞、檢視模型回覆，接著整合到你的應用程式。",
    protocol: "文字 / 單輪請求",
    steps: ["選擇模型", "輸入 API 金鑰", "撰寫提示詞"],
    advanced: "進階設定",
    advancedNote: "系統指令與輸出上限",
    examplesTitle: "從實際情境開始",
    examplesNote: "只填入提示詞，不會自動傳送。",
    presets: [
      { id: "plan", icon: "↗", title: "比較方案取捨", detail: "把需求整理成決策依據。", prompt: "我們正在為 12 人團隊建立客服助理。請比較使用模型 API 與自行部署開放模型兩種方案。我們需要在六週內推出、處理公司內部文件，並盡量降低維運負擔。請提供精簡的決策比較表、列出你的假設，並建議做決定前需要驗證的事項。" },
      { id: "code", icon: "⌘", title: "檢查程式問題", detail: "找出原因，說明修正方式。", prompt: "請檢查下列 JavaScript 函式是否正確。解釋問題、提供修正版，並建議一個能抓出此問題的測試。\n\nasync function loadUsers(ids) {\n  const users = [];\n  ids.forEach(async (id) => {\n    const response = await fetch('/users/' + id);\n    users.push(await response.json());\n  });\n  return users;\n}" },
      { id: "extract", icon: "{ }", title: "擷取結構化資料", detail: "讓零散筆記成為明確資料。", prompt: "請將以下虛構專案筆記轉成有效的 JSON，不要附加說明。欄位為 project、owner、deadline、decisions（陣列）、open_questions（陣列）。缺少的值請使用 null，不要自行補充。\n\nAtlas 專案：設計團隊負責原型，目標交付日為 2026-10-15。已決定首版支援英文與繁體中文，且必須提供手機版排版。部署方式與最終預算尚待確認。" },
    ],
    needsKey: "請先輸入 API 金鑰",
    invalidKey: "請確認 API 金鑰格式",
    needsPrompt: "請先撰寫提示詞",
    invalidTokens: "請確認輸出 Token 上限",
    canSend: "可以傳送請求",
    characters: "字元",
    copyResponse: "複製回覆",
    responseCopied: "已複製回覆",
    responseCopyFailed: "請選取回覆內容後手動複製。",
    requestTime: "請求耗時",
    codeLanguages: "程式碼語言",
    runtimes: { curl: "終端機 · cURL", python: "Python 3 · 標準函式庫", javascript: "Node.js · 儲存為 .mjs" },
    setup: "請求設定",
    model: "模型",
    textOnly: "此處僅支援文字請求。視覺、圖像與音訊輸入請參考 API 文件。",
    key: "API 金鑰",
    keyPlaceholder: "輸入你的 PowerChampion API 金鑰",
    keyNote:
      "金鑰僅留在此頁面的記憶體，傳送請求時才轉送至 PowerChampion 閘道。此工作台不會儲存金鑰。",
    clearKey: "清除金鑰",
    getKey: "取得 API 存取",
    status: "查看服務狀態",
    system: "系統指令",
    optional: "選填",
    systemPlaceholder: "你是一位助理，請用清楚且簡潔的方式回答。",
    tokens: "最大輸出 Token 數",
    tokensNote: "可設定 1–4,096 Tokens，實際用量由模型回覆決定。",
    prompt: "你的提示詞",
    promptPlaceholder: "你想探索什麼？",
    singleTurn: "單輪請求",
    example: "使用範例",
    examplePrompt:
      "用兩句話解釋 API 如何運作，再舉一個適合小型企業的實際應用。",
    send: "傳送 API 請求",
    sending: "等待模型回覆…",
    cancel: "取消請求",
    billed: "請求會使用你的 API 額度並可能產生費用，包含已取消或逾時的請求。",
    result: "模型回覆",
    ready: "準備好就能開始",
    empty: "選擇模型、輸入金鑰並傳送提示詞，實際的模型回覆會顯示在這裡。",
    waiting: "你選擇的模型正在處理請求。",
    waitingNote: "最長等待 45 秒，你可以隨時取消。",
    input: "輸入 Tokens",
    output: "輸出 Tokens",
    total: "總 Tokens",
    unavailable: "未回報",
    usageNote: "Token 數由閘道回報，實際計費請查看額度餘額。",
    balance: "查看餘額",
    reasoning: "模型推理",
    noContent:
      "模型回傳了推理內容，但沒有最終回答。可嘗試提高輸出 Token 上限。",
    truncated: "回覆已達到輸出 Token 上限，如需更長回覆可提高上限。",
    filtered: "模型將此回覆標記為已過濾。",
    code: "請求程式碼",
    copy: "複製程式碼",
    copied: "已複製",
    copyFailed: "目前無法自動複製，請選取程式碼後手動複製。",
    codeNote:
      "請在環境變數設定 POWERCHAMPION_API_KEY。範例會依上方設定更新，並排除你的金鑰。",
    docs: "閱讀 API 文件",
    cancelled: "已取消請求，閘道仍可能計入已使用的用量。",
    errors: {
      authentication: "請確認 API 金鑰有效，且有權使用此模型。",
      credits: "此金鑰的額度不足，請查看餘額或聯繫支援儲值。",
      rate_limit: "閘道正在限制請求頻率，請稍後再試。",
      timeout: "請求已逾時。重試前請先查看服務狀態，已使用的用量仍可能計費。",
      input: "請確認金鑰、提示詞與輸出 Token 上限設定。",
      too_large: "請求內容過長，請縮短提示詞與系統指令。",
      origin: "無法驗證此請求，請重新整理頁面後再試。",
      response: "閘道沒有回傳可用的文字回覆，請查看服務狀態或改用其他模型。",
      gateway: "模型閘道目前無法使用或無法完成請求，請先查看服務狀態再試。",
      network: "請求無法連上閘道，請檢查網路與服務狀態，避免連續重試。",
    },
  },
};
